version: "3.9"

services:
  travel-bot:
    build: .
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    env_file:
      - .env
    command: >
      sh -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 &
      streamlit run travel_ui.py --server.port 8501 --server.address 0.0.0.0
      "
